### PR TITLE
PR: Attribute is listed twice in the docstring for IES TM-27-14's "Element_Specification_IESTM2714" class.

### PR DESCRIPTION
**Pull request by JGoldstone**
…_Specification_IESTM2714 ctor.

### CODE REVIEW

**Comment by KelSolaar** [comment]
Thanks @JGoldstone, we should probably remove the first instance actually so that they appear in the order of the signature.

**Comment by JGoldstone** [comment]
Oops, yes. This being my first PR submission [maybe anywhere, or close enough] I have to ask: how does refinement work? Do you make the proposed change to the PR (and I completely agree with you as to the modification)? Or do I, and somehow resubmit?

**Comment by KelSolaar** [comment]
Ideally, you would implement the changes in a subsequent commit, and we can merge it! In that case, to keep the history tidy, I would squash the two commits in a single one!

**Comment by KelSolaar** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- colour/characterisation/correction.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/colour-science/colour/pullRequest?prid=6220202&bid=20276664)

**Comment by JGoldstone** [comment]
Can you do the squashing on your side (maybe you were already offering that with your ‘I would’)?

I feel like I’ve already done enough damage and recovery to my fork today (lots of learning about reset —hard and push —force) and if you can take it from here I’d appreciate it.

**Comment by KelSolaar** [comment]
Thanks yes! Merging :)

**Pull request merged**
