### PR TITLE
PR: Implement missing number of terms from Cheung's (2004) polynomial transforms

### LINKED ISSUE #616: Cheung (2004): Transforms with 4 and 35 terms not implemented.
Cheung et al. [1] define polynomial transforms with the following numbers of terms:
- 3
- 4 (not implemented)
- 5
- 10
- 20
- 35 (not implemented)

I just noticed that 4 and 35 terms are not supported by ``augmented_matrix_Cheung2004``. Is this intentional, and if yes, why? If not, I can implement the missing options (i.e. create a pull request).

[1] A comparative study of the characterisation of color cameras by means of neural networks and polynomial transforms, 2004 - https://www.researchgate.net/publication/227522365_A_comparative_study_of_the_characterisation_of_color_cameras_by_means_of_neural_networks_and_polynomial_transforms

### PR DESCRIPTION
**Pull request by chnmasta05**
# Summary

Fixes #616.

# Preflight

**Code Style and Quality**

- [x] Unit tests have been implemented and passed.
- [x] Pyright static checking has been run and passed.
- [x] Pre-commit hooks have been run and passed.
- [N/A] New transformations have been added to the *Automatic Colour Conversion Graph*.
- [N/A] New transformations have been exported to the relevant namespaces, e.g. `colour`, `colour.models`.

**Documentation**

- [N/A] New features are documented along with examples if relevant.
- [x] The documentation is [Sphinx](https://www.sphinx-doc.org/en/master/) and [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant.

### CODE REVIEW

**Comment by KelSolaar** [comment]
Awesome and thanks a lot @chnmasta05!

**Comment by KelSolaar** [comment]
Do you have a contributor name you would like for citation purposes? https://zenodo.org/record/7367239

**Comment by chnmasta05** [comment]
Thank you! Please use Xiaohan Chen as my name, where Chen is the surname.

**Comment by KelSolaar** [comment]
Awesome thanks!

**Pull request merged**
