### PR TITLE
PR: Support for LUT Inversion.

### PR DESCRIPTION
**Pull request by njwardhan**
Opening a cleaner version of the earlier PR (#622), which implements support for LUT Inversion in Colour Science.

### CODE REVIEW

**Comment by KelSolaar** [comment]
@njwardhan : I just rebased on top of develop and force-pushed back to your fork!

**Comment by zachlewis** [comment]
Glorious. Thank you both.

@nick-shaw, I'd love to implement a similar interface for the CLF nodes... what do you think?
Has anyone taken a stab at inverting monotonic half-domain LUTs? Half-domain stuff breaks my brain...

**Comment by KelSolaar** [comment]
I haven't look at the HalfDomain thingy but I'm cleaning up the PR while trying to understand where things were left at. Fact that Slack history is disappearing does not help at all!

**Comment by KelSolaar** [comment]
@zachlewis, @nick-shaw : I haven't tested with images yet but this should be in a good place!

**Comment by KelSolaar** [comment]
Putting this notebook here for future reference: https://colab.research.google.com/drive/1sKr2GlqEl1MDgsaHguBuzEAx7yPSvgy7?usp=sharing

**Comment by KelSolaar** [comment]
We have experienced segmentation faults using Scipy when building the KDTree, i.e. https://github.com/scipy/scipy/issues/14074, thus an alternative is to use `sklearn`: 5767ef96eaa10d0f072457898b7ed13aa8c25ad1

**Comment by priikone** [comment]
I wanted see if I could inverse ACEScct to linear LUT, but didn't have much luck.  Perhaps I'm missing something.  Here's the code:

```
domain = [0, 1.4679964]
LUT = LUT1D(size=4096, name='ACEScct to Linear', domain=domain)
LUT.table = log_decoding_ACEScct(LUT.table)
print(LUT)

RGB = np.array([[0.18, 0.18, 0.18], [65504, 65504, 65504]])
print(RGB)
RGB = log_encoding_ACEScct(RGB)
print(RGB)
RGB = LUT.apply(RGB)
print(RGB)
RGB = LUT.apply(RGB, direction='Inverse')
print(RGB)
RGB = log_decoding_ACEScct(RGB)
print(RGB)
```
And the result:

```
LUT1D - ACEScct to Linear
-------------------------

Dimensions : 1
Domain     : [ 0.         1.4679964]
Size       : (4096,)
[[     0.18      0.18      0.18]
 [ 65504.    65504.    65504.  ]]
[[ 0.4135884   0.4135884   0.4135884 ]
 [ 1.46799631  1.46799631  1.46799631]]
[[     0.18000035      0.18000035      0.18000035]
 [ 65504.00015204  65504.00015204  65504.00015204]]
[[    0.44520081     0.44520081     0.44520081]
 [ 5401.31762442  5401.31762442  5401.31762442]]
...colour/colour/models/rgb/transfer_functions/aces.py:503: RuntimeWarning: overflow encountered in power
  2 ** (ACEScct * 17.52 - 9.72),
[[ 0.26423954  0.26423954  0.26423954]
 [        inf         inf         inf]]
```

**Comment by KelSolaar** [comment]
Hi @priikone,

Thanks, it is worth keeping in mind that the proper domain should be [0, 1] for your first variable creation, not [0, 1.4679964]. Anyway, I looked at our implementation and it was not working properly nonetheless, would you mind testing the latest commit please?


```python
In [1]: import numpy as np
   ...: import colour
   ...: LUT = colour.LUT1D(size=4096, name='ACEScct to Linear')
   ...: LUT.table = colour.models.log_decoding_ACEScct(LUT.table)
   ...: RGB = np.linspace(0, 1, 10)
   ...: print(RGB)
   ...: RGB_a = LUT.apply(RGB)
   ...: print(RGB_a)
   ...: print(LUT.apply(RGB_a, direction='Inverse'))
[ 0.          0.11111111  0.22222222  0.33333333  0.44444444  0.55555556
  0.66666667  0.77777778  0.88888889  1.        ]
[ -6.91687759e-03   3.62473578e-03   1.76197020e-02   6.79209289e-02
   2.61823531e-01   1.00928480e+00   3.89061979e+00   1.49976719e+01
   5.78134529e+01   2.22860944e+02]
[ 0.          0.11111111  0.22222222  0.33333333  0.44444444  0.55555556
  0.66666667  0.77777778  0.88888889  1.        ]
```

**Comment by priikone** [comment]
Thanks @KelSolaar.  Works now!

> Thanks, it is worth keeping in mind that the proper domain should be [0, 1] for your first variable creation, not [0, 1.4679964]. 

Hmm... So that will produce a LUT with max 222.68 output value.  How would I create a LUT in 0-1 domain for full 0-65504 output? 

I tested this with CLF and ociochecklut as well.  For full 0-1.4679964 ACEScct input the max output is 222.681.  OTOH, one could scale the input ACEScct value down to 0-1 range and have the LUT output 65504 as max value.  I tested that too and I get correct values out.  Colour works a bit differently; it interpolates beyond the 222.68 and the 1.4679964 comes out as 1487.57445268, but the inverse works.

What is the "proper" way of doing this?  Sorry, this isn't exactly related to this PR...

**Pull request merged**
