### PR TITLE
PR: Implement support for "HCL" colourspace.

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Added two of the functions provided in #564s comments.

Please review the comments that I made as I am just starting and they might be wrong, and I couldn't figure out what to add in the 'notes' section, specifically in the range part. It would be great if anyone can guide me.

Thank you

### CODE REVIEW

**Comment by Saransh-cpp** [comment]
Whenever a reviewer gets some free time, please review the PR and let me know why the tests failed. I'll fix them as soon as possible.

I was going through the failures and there were some tests like the one attached below, where the output is somewhat correct but I don't know how to correctly implement that.

image

Thank you so much:)

**Comment by KelSolaar** [comment]
Hi @Saransh-cpp,

Thanks for this PR!

I Haven't had time to look at the code but you have an extra space before the bracket:

> 283... ]

Should be:

> 283...]

**Comment by Saransh-cpp** [comment]
> Hi @Saransh-cpp,
> 
> Thanks for this PR!
> 
> I Haven't had time to look at the code but you have an extra space before the bracket:
> 
> > 283... ]
> 
> Should be:
> 
> > 283...]

Fixed it! Thank you for the guidance.

**Comment by KelSolaar** [comment]
Try that: 

> array([-0.0316785...,  0.2841715...,  0.2285964...])

**Comment by KelSolaar** [comment]
Hi @Saransh-cpp,

The doctests should be fixed! I will annotate a few things!

**Comment by KelSolaar** [comment]
Thanks @Saransh-cpp!

Besides the comments I left in the code, we would need to add:

- Unit tests in `colour/models/rgb/tests/test_cylindrical.py`
- Imports in `colour/models/rgb/__init__.py` and `colour/__init__.py`
- Addition to the graph: `colour/graph/conversion.py`
- Documentation entries added to `docs/colour.models.rst`
- Maybe some examples in `colour/examples/models/examples_cylindrical.py`

**Comment by Saransh-cpp** [comment]
Thanks @KelSolaar!

I will start working on these things one by one!

**Comment by Saransh-cpp** [comment]
> Thanks @Saransh-cpp!
> 
> Besides the comments I left in the code, we would need to add:
> 
> * Unit tests in `colour/models/rgb/tests/test_cylindrical.py`
> * Imports in `colour/models/rgb/__init__.py` and `colour/__init__.py`
> * Addition to the graph: `colour/graph/conversion.py`
> * Documentation entries added to `docs/colour.models.rst`
> * Maybe some examples in `colour/examples/models/examples_cylindrical.py`

@KelSolaar sorry for the extra time take, I was dealing with my internal examinations which are over now. I have added Unit test for RGB_to_HCL function and have added imports in both the files, I will work on other listed out things as soon as possible. (Hopefully the tests pass :") )

**Comment by Saransh-cpp** [comment]
The lines 395 and 396 in the new unit test are causing the tests to fail. I will look into it, please let me know if anyone can fix this. Thanks!

image

**Comment by KelSolaar** [comment]
@Saransh-cpp : I think you are missing the domain-range scale directives, i.e. `to_domain_1` and `from_range_1`, at input and output of the definitions, this is why the test break.

**Comment by Saransh-cpp** [comment]
> @Saransh-cpp : I think you are missing the domain-range scale directives, i.e. `to_domain_1` and `from_range_1`, at input and output of the definitions, this is why the test break.

I have added the missing domain-range scale directives but I have been struggling with committing my changes since a day. The terminal while committing shows -
```terminal
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'c:\users\saransh\appdata\local\pypoetry\cache\virtualenvs\colour-kbwigdau-py3.8\scripts\python.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'c:\\users\\saransh\\appdata\\local\\pypoetry\\cache\\virtualenvs\\colour-kbwigdau-py3.8\\scripts\\python.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.executable = 'c:\\users\\saransh\\appdata\\local\\pypoetry\\cache\\virtualenvs\\colour-kbwigdau-py3.8\\scripts\\python.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'c:\\users\\saransh\\appdata\\local\\pypoetry\\cache\\virtualenvs\\colour-kbwigdau-py3.8\\scripts\\python38.zip',
    '.\\DLLs',
    '.\\lib',
    'c:\\users\\saransh\\anaconda3',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00002d48 (most recent call first):
<no Python frame>
```

First I thought that there were some issues with my python configurations but I tested it in my own projects and everything worked fine. My path variables are also set and I tried looking for the solution on GitHub and Stackoverflow but most of them were suggesting to add python in the path which is already present in my case.

Is it something related to my setup or with the repository in general which is causing this issue?

**Comment by KelSolaar** [comment]
Hi @Saransh-cpp,

Seems like your Python is not in a great state, can you launch the executable in `c:\\users\\saransh\\appdata\\local\\pypoetry\\cache\\virtualenvs\\colour-kbwigdau-py3.8\\scripts\\python.exe`?

Is it working at all?

Cheers,

Thomas

**Comment by Saransh-cpp** [comment]
> Hi @Saransh-cpp,
> 
> Seems like your Python is not in a great state, can you launch the executable in `c:\\users\\saransh\\appdata\\local\\pypoetry\\cache\\virtualenvs\\colour-kbwigdau-py3.8\\scripts\\python.exe`?
> 
> Is it working at all?
> 
> Cheers,
> 
> Thomas

Right now it isn't working at all, gives the same error. I uninstalled anaconda recently, could that be the reason for all this mess?

**Comment by Saransh-cpp** [comment]
Thanks, @KelSolaar, I will re-install everything again and create a new PR with the same code. Closing this PR.

**Comment by Saransh-cpp** [comment]
> Thanks, @KelSolaar, I will re-install everything and create a new PR with the same code. Closing this PR.

**Comment by KelSolaar** [comment]
No need to close the PR, you just need a fresh environment, the code should work the same with it!

**Pull request closed without merging**
