### PR TITLE
PR: Improve CLF 3.0's "camera-log" function implementation. 

### PR DESCRIPTION
**Pull request by njwardhan**
This pull request allows the user to pass one extra argument: `linear_slope` to the `logarithmic_function_camera` definition, and thus makes the function more robust in handling different types of cases.

### CODE REVIEW

**Comment by KelSolaar** [comment]
@njwardhan : I haven't looked at the spec but two things for consistency:

```python
def logarithmic_function_quasilog(x,
                                  style='linToLog',
                                  base=2,
                                  log_side_slope=1,
                                  lin_side_slope=1,
                                  log_side_offset=0,
                                  lin_side_offset=0):
```

```python
def logarithmic_function_camera(x,
                                style='cameraLinToLog',
                                base=2,
                                linear_slope=None,  # <---
                                log_side_slope=1,
                                lin_side_slope=1,
                                log_side_offset=0,
                                lin_side_offset=0,
                                lin_side_break=0):
```

- `linear_slope=None,` should be moved after `lin_side_offset=0,`
- `linear_slope` should probably be named `lin_slope` to be consistent with the other arguments. How is it in the spec?

**Comment by KelSolaar** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ colour/recovery/jakob2019.py  -4
+ colour/recovery/tests/test_jakob2019.py  -1
         

Clones added
============
- colour/models/rgb/transfer_functions/tests/test_log.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/colour-science/colour/pullRequest?prid=5947522&bid=19496809)

**Comment by KelSolaar** [comment]
Seems like this PR has gotten into a messy state, I will take over and try to clean that a bit.

**Comment by KelSolaar** [comment]
And merged! :)

**Comment by zachlewis** [comment]
@njwardhan , this is really fantastic work. Thank you -- it's wonderful having the CLF algorithms as part of the standard colour library. 

A few months ago, I had done some work on implementing CLF nodes as AbstructLUTSequenceOperators, a-la @nick-shaw's ongoing feature/CLF branch. I had a little time yesterday to refactor my Log operator stuff to use these brand spankin' new logarithmic_function_camera / quasilog / basic methods, and it feels gooood. 

Coincidentally, I noticed yesterday that @nick-shaw had just a few days ago started picking up work in his own branch -- in particular, he's implemented an Exponent node and the methods for un/structuring to and from CLF, but hasn't started much work on Log. 

I'm hoping to submit a PR before the weekend to Nick's clf_temp branch that dovetails nicely with both the work he's done, as well as Nishant's work (cherry-picked from this PR).  

Stay tuned...

**Pull request merged**
