### PR TITLE
Implement support for ACEScct colourspace

### LINKED ISSUE #277: Implement support for "ACEScct" colourspace.
References
========

https://github.com/ampas/aces-dev/commit/13b9d6a643244823a723a6e5a97d3ff920b5d2dd

### PR DESCRIPTION
**Pull request by scoopxyz**
closes #277

### CODE REVIEW

**Comment by scoopxyz** [comment]
Worth discussing the [test_ACEScc_equivalency_log_encoding_ACEScct](https://github.com/colour-science/colour/commit/c1dfd05f18649adced8c04dde7cc5d35605f4c3e#diff-ffe121563e1f8454df88aeee7ab8fbb9R375) tests I added, as validation of [this](https://github.com/ampas/aces-dev/blob/v1.0.3/documents/LaTeX/S-2016-001/introduction.tex#L14) ACEScct parameter

**Comment by KelSolaar** [comment]
Thanks for the tests Sean! I think the `test_ACEScc_equivalency_log_encoding_ACEScct` test makes sense, I would probably make a reference to the Academy document so that people not aware of that know the very reason for the test.

**Comment by scoopxyz** [comment]
Right, Id thought about that but didn't know a clean way to implement it.
Should it just exist within the doc string for that function?

**Comment by KelSolaar** [comment]
Yep that should be fine, a small explanation with a reference to the document. Speaking of what, would you mind using that reference in place of the two you have used:

> The Academy of Motion Picture Arts and Sciences. (2016). Specification S-2016-001 - ACEScct, A Quasi-Logarithmic Encoding of ACES Data for use within Color Grading Systems. Retrieved October 10, 2016, from https://github.com/ampas/aces-dev/tree/v1.0.3/documents

It is almost the same except that there is the date of retrieval and it is coming from our reference manager.

**Comment by KelSolaar** [comment]
@scoopxyz : Thanks a lot Sean! Would it be possible to squash the two last commits into 71f790b (you will have to force push your branch) and then I'll merge the PR.

**Comment by scoopxyz** [comment]
I believe that I have the corrected the docs now

**Comment by KelSolaar** [comment]
Yes, would you mind squashing the two last commits into https://github.com/colour-science/colour/commit/71f790bf2b88d91e1d0e9257d95c2be413ac36bc?

Something like that would do: https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

Cheers,

**Comment by KelSolaar** [comment]
Thanks a lot @scoopxyz / Sean! Merged 👍

**Pull request merged**
