### PR TITLE
PR: Implement Nayatani Helmholtz–Kohlrausch Effect estimation method.

### PR DESCRIPTION
**Pull request by ilia3101**
I have implemented support for *Nayatani (1997)* "Simple Estimation Methods for the Helmholtz–Kohlrausch Effect".

There are a few things I'm not sure about yet:
- code style (if all docstring comments are correct, everything else as well)
- What I have added to `__init__.py` files
- If i have put it in the correct folder
- How things in the code should be split up, should there be one main function simply called 'hke' which takes an argument for which method to use? I decided against this for now because the different methods return values that work in different spaces (object method works on `L*`, and luminous method returns a factor for `Y`, and who knows what other papers might use), so there is two separate functions, one each for object and luminous colours.
- Citation key still needed
- Should `HKE` perhaps be capitalised in function names?
- Should I put my name in `__author__`?
- K_B_r and q(theta) coefficients are calculated in separate functions, originally I wrote it this way as both the object and luminous colour algorithms called them, but now it is not necessary to keep them as separate functions, but I guess having the functions separarely is good for testing and verifying that evrything works.

Please give feedback :)

### CODE REVIEW

**Comment by KelSolaar** [comment]
Hi @ilia3101,

Thanks for this PR, this is great! Overall it looks clean.

### code style (if all docstring comments are correct, everything else as well)

Yes, only a minor few things:

- We use `Yapf` for code formatting and it will clear your nice align work in `coefficient_q_Nayatani1997`.
- We used `flake8` for consistency with PEP8.
- The examples, unless the `# doctests +SKIP` is used are being run and their output is tested to match.
  - I would probably avoid the `from colour import *` in docstrings.
- We will need some other things:
  - Unit tests
  - Addition to the RST docs
  - Maybe and `example_hke.py` module in `colour.appearance.examples`?

### What I have added to __init__.py files

Fine with me!

### If i have put it in the correct folder

This is very much related to colour appearance, so I would probably move the code in the `colour.appearance` sub-package.

### How things in the code should be split up, should there be...

What you did is fine I think!

### Citation key still needed

- Citation Key: `Nayatani1997`
- Bibliography: `Nayatani, Y. (1997). Simple estimation methods for the Helmholtz—Kohlrausch effect. Color Research & Application, 22(6), 385–401. doi:10.1002/(SICI)1520-6378(199712)22:6<385::AID-COL6>3.0.CO;2-R`

### Should HKE perhaps be capitalised in function names?

Haaaaa, the naming convention conundrum! :) I would actually not mind a more explicit name, even if it is long, e.g.

`HelmholtzKohlrausch_effect_object_Nayatani1997`, it could go along with a hypothetical `Hunt_effect_Luo2034`.

### Should I put my name in __author__?

Sure thing!

### K_B_r and q(theta) coefficients are calculated in separate functions, originally...

Fine with keeping them separate!

Cheers,

Thomas

**Comment by ilia3101** [comment]
@KelSolaar Thanks so much for the review!

I will work on all of these points later today.

> This is very much related to colour appearance, so I would probably move the code in the `colour.appearance` sub-package.

Ah ok, I thought about putting it in appearance first, but I did not do it, as every file in that folder implements an entire appearance model, rather than a single effect like HKE. That's why I was quite unsure about where it should go. I ended up following the yellowness and whiteness files as a guideline.

**Comment by ilia3101** [comment]
I have added unit tests and an example in `colour.appearance.examples`. I have not figured out how to run and debug my specific unit test so I think it may not be working, as running all of them produces an error at the end, but doesn't tell me specifically where it comes from. But I have followed the other unit tests (and https://www.colour-science.org/contributing/) as a guide, so it should be almost there.

> Addition to the RST docs

Not sure about how to do this.

**Comment by KelSolaar** [comment]
Hello,

I attached a small patch that varnishes the implementation, was faster than commenting, mostly code formatting related things.

[0001-Improve-Helmholtz-Kohlrausch-effect-estimation-imple.patch.txt](https://github.com/colour-science/colour/files/6721351/0001-Improve-Helmholtz-Kohlrausch-effect-estimation-imple.patch.txt)

Are you running Yapf and Flake8?

Cheers,

Thomas

**Comment by KelSolaar** [comment]
BTW, do you want an invite on our Slack workspace?

**Comment by ilia3101** [comment]
Thanks for the patch, committed.

> Are you running Yapf and Flake8?

No I have not tried those yet. I will try to get them running. Those are the tools used for formatting/checking code in this project?

> BTW, do you want an invite on our Slack workspace?

That would be awesome!

**Comment by ilia3101** [comment]
BTW your commit was pretty huge! How much of it was manual work and how much yapf/flake8?

**Comment by KelSolaar** [comment]
> BTW your commit was pretty huge! How much of it was manual work and how much yapf/flake8?

Yapf will only auto-format, most of the things I picked up are from PyCharm inline inspections which roughly combine Pylint and Flake8 and then the habit of reviewing our codebase. Reading the paper and connecting the definitions to the equations was probably the longest task! :)

Will send you an invite now, thanks for the great work!

**Comment by ilia3101** [comment]
Thank you.

Now I just need to figure out why the unit test for q is failing (good thing they exist)

**Comment by KelSolaar** [comment]
Seems like the pre-computed value is not correct:

```
======================================================================
FAIL: Tests :func:`colour.appearance.coefficient_q_Nayatani1997`
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/colour/colour/colour/appearance/tests/test_hke.py", line 247, in test_n_dimensional_coefficient_q_Nayatani1997
    coefficient_q_Nayatani1997(theta), q, decimal=7)
  File "/Users/runner/Library/Caches/pypoetry/virtualenvs/colour-wncfrUff-py3.6/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 579, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/Users/runner/Library/Caches/pypoetry/virtualenvs/colour-wncfrUff-py3.6/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 1044, in assert_array_almost_equal
    precision=decimal)
  File "/Users/runner/Library/Caches/pypoetry/virtualenvs/colour-wncfrUff-py3.6/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 7 decimals

Mismatched elements: 6 / 6 (100%)
Max absolute difference: 0.06384110316967176
Max relative difference: 0.45762574525152017
 x: array([ 0.2033462,  0.2033462,  0.2033462,  0.2033462,  0.2033462,
        0.2033462])
 y: array([ 0.1395051,  0.1395051,  0.1395051,  0.1395051,  0.1395051,
        0.1395051])
```

Looking at the n-dimensional tests, we might also need to test whether a 3-dimensional array, e.g. image goes through.

**Comment by ilia3101** [comment]
@KelSolaar Thanks for looking at this. Looks like multi-dimensional isn't working right (?).

> Looking at the n-dimensional tests, we might also need to test whether a 3-dimensional array, e.g. image goes through.

Sounds like a good idea. I will try this out today.

Sorry about the long delay.

**Comment by ilia3101** [comment]
Well, I have fixed this issue. Slightly embarrassing mistake: https://github.com/colour-science/colour/pull/824/commits/aae343c66f0ae4921b884d834434ce8ec0f06d64

**Comment by ilia3101** [comment]
> Looking at the n-dimensional tests, we might also need to test whether a 3-dimensional array, e.g. image goes through.

I wrapped `tile`/`assert_almost_equal` sections in an `for i in range (2):` to create 3-dimensional tests https://github.com/colour-science/colour/pull/824/commits/96697f82f0c9ff44e27f7980cf233c8616fce158

**Comment by KelSolaar** [comment]
Thanks @ilia3101! :)

**Pull request merged**
