### PR TITLE
PR: Implement support for Nikon Corporation N-Log / N-Gamut.

### PR DESCRIPTION
**Pull request by sobotka**
Add Nikon Corporation 2018 N-Log / N-Gamut.

Nikon. (2018). N-Log Specification
    Document Ver.1.0.0
    http://download.nikonimglib.com/archive3/\
    hDCmK00m9JDI03RPruD74xpoU905/N-Log_Specification_(En)01.pdf

### CODE REVIEW

**Comment by KelSolaar** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- colour/models/rgb/transfer_functions/nikon_nlog.py  3
         

Clones added
============
- colour/models/rgb/transfer_functions/nikon_nlog.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/colour-science/colour/pullRequest?prid=5458882&bid=17892647)

**Comment by KelSolaar** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- colour/models/rgb/transfer_functions/nikon_nlog.py  3
         

Clones added
============
- colour/models/rgb/transfer_functions/nikon_nlog.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/colour-science/colour/pullRequest?prid=5458882&bid=17892647)

**Comment by KelSolaar** [comment]
@sobotka : That should be ready to merge I think now!

@nick-shaw : Might want to drop a casual eye when you have 5 minutes please :)

**Review by nick-shaw — COMMENTED** [review]
I may be confused, but I am not sure why the addition of ISO 17321-1 to the bibliography appears to be included in one of the N-Log / N-Gamut commits.
Also, I wonder if it might be better to define N-Gamut simply using the BT.2020 primaries and white point, rather than defining them directly as if it was a separate colour space.
Other than that, looks good to me.

**Comment by sobotka** [comment]
@nick-shaw Agree in the BT.2020 case. I was sort of following the ideas that were previously existing. I think the rule should likely become “If another set of primaries / transfer / etc describes the new item precisely, reuse it”.

Seems sane?

**Comment by KelSolaar** [comment]
> I may be confused, but I am not sure why the addition of ISO 17321-1 to the bibliography appears to be included in one of the N-Log / N-Gamut commits.

A side-effect of the fact that when I exported the Bibliography for N-Log some new items squeezed in-between the time the branch was made and the time I did the export. I will drop the edit on the file and re-export in a `feature/v0.4.0` commit after the merge. Updating the primaries to reflect BT.2020 basis.

**Review by nick-shaw — APPROVED** [review]
Looks good to me.

**Comment by KelSolaar** [comment]
Thanks @nick-shaw! Merging! :)

**Pull request merged**
