### PR TITLE
PR: Use `shape` if passed, to also reshape the `colour.continuous.AbstractContinuousSignal` sub-classes in `colour.colorimetry.sd_to_XYZ_integration` definition.

### PR DESCRIPTION
**Pull request by KelSolaar**
# Summary

This PR ensures that the `shape` argument, if passed, is also used to reshape the `colour.continuous.AbstractContinuousSignal` sub-classes in `colour.colorimetry.sd_to_XYZ_integration` definition.

References #1247.

# Preflight

**Code Style and Quality**

- [N/A] Unit tests have been implemented and passed.
- [x] Pyright static checking has been run and passed.
- [x] Pre-commit hooks have been run and passed.
- [N/A] New transformations have been added to the _Automatic Colour Conversion Graph_.
- [N/A] New transformations have been exported to the relevant namespaces, e.g. `colour`, `colour.models`.

**Documentation**

- [x] New features are documented along with examples if relevant.
- [x] The documentation is [Sphinx](https://www.sphinx-doc.org/en/master/) and [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant.

### CODE REVIEW

**Comment by KelSolaar** [comment]
Something is broken, I will take a look tonight!

**Comment by tjdcs** [comment]
@KelSolaar While you are looking at this can you also check that the `ArrayLike` inputs actually get converted to an array before the caching check in `sd_to_XYZ`? I noticed that if you pass in a `list[float]` the method fails. I think it just needs an `asarray` somewhere before calling `tobytes()` (when xxhash is installed)

**Comment by KelSolaar** [comment]
Should be done!

**Comment by KelSolaar** [comment]
Going to merge this one @tjdcs!

**Pull request merged**
