### PR TITLE
PR: Implement support for "DaVinci Intermediate" log encoding.

### PR DESCRIPTION
**Pull request by KelSolaar**
Replaces #660 as @fredsavoir deleted the branch.

We might actually merge it "ad interim" now that the commits are squashed and do not affect the gamut primaries. Still requires various documentation updates, etc... before though.

### CODE REVIEW

**Comment by KelSolaar** [comment]
I think this is ready for review, quite a bit of code formatting and consistency improvements. Worth noting that the functions are OETF / OETF-1 and not log encoding curves.

**Comment by zachlewis** [comment]
> Worth noting that the functions are OETF / OETF-1 and not log encoding curves.

Just to be crystal clear, these should be reclassified as log encoding / decoding functions, and shouldn't remain OETF / OETF-1, correct?

**Comment by KelSolaar** [comment]
No the reverse, they were classified as log encoding but Blackmagic states it is an OETF and its inverse, so I renamed Fred's definitions to reflect that.

**Comment by nick-shaw** [comment]
How do we define if something is an OETF or a log encoding? Is it just based on what the published documentation calls it? A log encoding **is** one form of OETF, isn't it? In general we have OETFs for those where the input is in the 0-1 range, and log encoding for scene-referred HDR, don't we? The BMD paper is a bit confusing, because it refers to nits as if it is an inverse EOTF, but Resolve Colour management clearly treats it as a scene referred working space, applying tone and gamut mapping by default when converting to display referred.

**Comment by KelSolaar** [comment]
> How do we define if something is an OETF or a log encoding? Is it just based on what the published documentation calls it? A log encoding is one form of OETF, isn't it?

I would say that if the vendor explicitly states it is an OETF, we should not call it something else because it is what less tech savvy people will refer to and even though it might be incorrect, it will only serve confusion! Should BMD change their "naming convention", we could/should change it accordingly.

**Comment by fredsavoir** [comment]
Fully agree .

Thanks

Fred

**Review by nick-shaw — COMMENTED** [review]
Looks good to me. My only comment would be that there are redundant brackets in `davinci_intermediate.py` line 164. `(2 ** ((V / DI_C) - DI_B)) - DI_A` could be written `2 ** ((V / DI_C) - DI_B) - DI_A`.
And do we not bother including XYZ matrices from the white paper in the colour space definition if the ones derived from the primaries match to the number of decimal places given in the paper?

**Comment by KelSolaar** [comment]
Thanks @nick-shaw!

> `(2 ** ((V / DI_C) - DI_B)) - DI_A` could be written `2 ** ((V / DI_C) - DI_B) - DI_A`.

Ah! I think it might have come when Fred copied the reference implementation from the Whitepaper as it used the `power` function. I have just removed them!

Interestingly enough, I got used to PyCharm hinting when they are redundant but it seems like here it does not work, maybe broken functionality in my current version.

> And do we not bother including XYZ matrices from the white paper in the colour space definition if the ones derived from the primaries match to the number of decimal places given in the paper?

I will add them in a separate commit!

**Pull request merged**
