### PR TITLE
PR: Implement support for Rayleigh-Jeans spectral distribution.

### PR DESCRIPTION
**Pull request by Alt-Shivam**
For issue #919
Feedback Appreciated

### CODE REVIEW

**Comment by KelSolaar** [comment]
Hi @Alt-Shivam,

I would suggest to wait a bit that I merge the v0.4.0 branch, there is a lot of stuff happening atm and it is going to be hard for you to get your code in until I'm done! Let's cherry-pick your commit when the storm has passed!

Cheers,

Thomas

**Comment by Alt-Shivam** [comment]
@KelSolaar No worries sir
Just let me know when you're ready.
Thanks 😊

**Comment by KelSolaar** [comment]
I think it should be fairly stable at this point. Update `develop` on your fork, start a new `feature/rayleigh_jeans` branch from it, then cherry-pick your commit from `feature/v0.4.0`. You will have some conflicts but they should not be too hard to cleanup. Let me know how it goes.

**Comment by Alt-Shivam** [comment]
Ok sir.

**Comment by Alt-Shivam** [comment]
-Update-
Sir Should I continue to create a new PR 
and which branch should I choose to    develop or feature/v0.4.0
image

**Comment by KelSolaar** [comment]
@Alt-Shivam : Yes this is exactly it!

**Pull request closed without merging**
