### PR TITLE
PR: Implement support for *HyCH* large color difference

### PR DESCRIPTION
**Pull request by mesvam**
# Summary

# Preflight

**Code Style and Quality**

- [x] Unit tests have been implemented and passed.
- [x] Pyright static checking has been run and passed.
- [x] Pre-commit hooks have been run and passed.
- [ ] New transformations have been added to the _Automatic Colour Conversion Graph_.
- [x] New transformations have been exported to the relevant namespaces, e.g. `colour`, `colour.models`.

**Documentation**

- [x] New features are documented along with examples if relevant.
- [x] The documentation is [Sphinx](https://www.sphinx-doc.org/en/master/) and [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant.

### CODE REVIEW

**Comment by KelSolaar** [comment]
Hey @mesvam,

I squashed your commits from the previous branch so you would need to create a new branch from `develop`, cherry-pick 21823bac200604b973ed2e51769016e1c5af3260, and force-push that branch back to [mesvam:feature/HyCH](https://github.com/mesvam/colour/tree/feature/HyCH).

I will take a look at the paper but reading what you wrote LCH should really just be Lab converted to LCHab. We have it there `colour.models.Lab_to_LCHab` BUT it is programmatically generated thus not visible explicitly in the codebase: https://github.com/colour-science/colour/blob/363145a3d57a95bac68b241a2997f4617198f6a0/colour/models/__init__.py#L470

**Comment by KelSolaar** [comment]
I will need to add an intermediate definition so that we do not copy-paste the entire CIE 2000 code here.

**Comment by KelSolaar** [comment]
Hello,

I added a new `colour.difference.delta_e.intermediate_attributes_CIE2000` definition that should have all the required attributes and avoid code duplication.

Let me us know how it goes!

Cheers,

Thomas

**Comment by KelSolaar** [comment]
Thanks a lot, I will merge in a staging branch and doctor the history a bit.

**Comment by mesvam** [comment]
> Also, Equation 6 for CD4 is notated using L*C*H* in the paper, but I'm seeing L'C'H' used in other sources and also in this package. I'm assuming when the paper uses ΔC*, they mean ΔC' because of the k_C * S_C denominator, but I'm not confident in this. And also since the paper doesn't provide any examples, I can't find any sample data to compare results to verify my implementation.

So I contacted the authors, who kindly provided some test data to compare. I verified that this implementation matched their results to within numerical precision, with the exception of an optional hue rotation term.

You can cherry-pick this https://github.com/mesvam/colour/commit/273031877bd977f19d449e62111080a5f2a2e4b5 if you want to add it to the test suite

**Pull request merged**
