### PR TITLE
PR: Implement support for "ITUR BT.2100-2".

### PR DESCRIPTION
**Pull request by KelSolaar**
References #450.

### CODE REVIEW

**Comment by KelSolaar** [comment]
@nick-shaw : I removed the clamp compared to the reference, I was not comfortable having that middle of the functions.

**Comment by nick-shaw** [comment]
> @nick-shaw : I removed the clamp compared to the reference, I was not comfortable having that middle of the functions.

I guess that makes sense. For a real display there is no meaning to an EOTF producing a negative value, whereas when performing calculations for various purposes there may be a reason to preserve negatives. And the user can always clamp negative values themselves.

Not sure it helps with invertibility though, since **_OETF<sup>-1</sup>(x)_** where **_x < 0_** will be the same as **_OETF<sup>-1</sup>(-x)_**, since **_OETF<sup>-1</sup>(x) = x<sup>2</sup> / 3_** when **_x <= 0.5_**.

Might there be a case for replacing `(E_p / r) ** 2` with e.g. `gamma_function((E_p / r), 2, negative_number_handling='mirror'` in `oetf_reverse_ARIBSTDB67` to allow for invertibility?

**Comment by KelSolaar** [comment]
Yes that makes sense, we should also change the square root in the OETF accordingly: `r * np.sqrt(E)`.

I will do the changes.

**Comment by nick-shaw** [comment]
https://github.com/colour-science/colour/blob/d2e2158d5b1f831cdf6e315f7b77572f6cdb6e5c/colour/models/rgb/transfer_functions/itur_bt_2100.py#L471
Shouldn't this be `return oetf_ARIBSTDB67(12 * 0.5, constants=BT2100_HLG_CONSTANTS)` to make use of the calculated constants? Likewise for line 516?

**Comment by nick-shaw** [comment]
It looks like the HLG OOTF has not been changed for BT.2100-2. As far as I can see, both methods use the same `ootf_HLG_BT2100` which is not correct. When you use a non-zero `L_B` the output for zero input should track `L_B`, which it currently doesn't.

```
>>> eotf_HLG_BT2100(0.0, L_B=0.5, L_W=1000,  method='ITU-R BT.2100-2')
0.99975000000000014
```

**Comment by KelSolaar** [comment]
Mmmh, the black lift should be applied once:

```
>>> colour.models.eotf_HLG_BT2100(0.212132034355964, 0.01)
eotf_HLG_BT2100(0.212132034355964, 0.01)
  eotf_HLG_BT2100_2(0.212132034355964, 0.01, 1000, None)
    black_level_lift_HLG_BT2100(0.01, 1000, None)
      gamma_function_HLG_BT2100(1000)
    ootf_HLG_BT2100(0.016635216736461608, 0.01, 1000, None)
      gamma_function_HLG_BT2100(1000)
7.3421242063785908
```

I will double-check tonight.

**Comment by KelSolaar** [comment]
So I totally missed the fact that the OOTF has been also changed:

BT-2100-1
---

image

BT-2100-2
---
image

**Comment by KelSolaar** [comment]
> https://github.com/colour-science/colour/blob/d2e2158d5b1f831cdf6e315f7b77572f6cdb6e5c/colour/models/rgb/transfer_functions/itur_bt_2100.py#L471
> 
> 
> Shouldn't this be `return oetf_ARIBSTDB67(12 * 0.5, constants=BT2100_HLG_CONSTANTS)` to make use of the calculated constants? Likewise for lines 516, 615 and 677?

We put the following comment for `colour.models.rgb.transfer_functions.itur_bt_2100.BT2100_HLG_CONSTANTS` attribute docstring:

```
*Recommendation ITU-R BT.2100* *Reference HLG* constants expressed in their
analytical form in contrast to the *ARIB STD-B67 (Hybrid Log-Gamma)* numerical
reference.

Those constants are not currently in use and are provided as a reference only.
```

So we elected not to use the analytical form, should we change it?

**Pull request merged**
