### PR TITLE
PR: Implement support for Y'CbCr matrices generation.

### PR DESCRIPTION
**Pull request by KelSolaar**
References #486.

### CODE REVIEW

**Comment by KelSolaar** [comment]
@nick-shaw : Might be worth one of your eyes! :)

**Comment by ValZapod** [comment]
Couple of points and/or references: in [Supplement 18](https://www.itu.int/itu-t/recommendations/rec.aspx?id=13441&lang=en) of ITU-T (page 24) a matrix with 14 digits after decimal point is given and is to be used for Y′CbCr to R′G′B′.

The second point is that I recommend doing immediately xvYCC colorspace. That is the negative values from XYZ to RGB (linear RGB that this) are further defined while the 601 and 709 stuff stays the same. That is the standard nowadays. Used in Kodak Photo CD and is used now very often in HDMI.
I will attach the latest version of the standard (with all errata), the matrix from XYZ to RGB and non-linearity transfer function (just a continuation of the very same BT.709 and BT.601 transfer function) are in 5.3. 

I will also point out that "for TransferCharacteristics equal to 1, 6, 14 or 15, α has the value 1 + 5.5 * β = 1.099296826809442... and β has the value 0.018053968510807...." and 0.099 value is just 1 - α. That is from H.273.

**Comment by nick-shaw** [comment]
> Couple of points and/or references: in [Supplement 18](https://www.itu.int/itu-t/recommendations/rec.aspx?id=13441&lang=en) of ITU-T (page 24) a matrix with 14 digits after decimal point is given and is to be used for Y′CbCr to R′G′B′.

This function would be able to calculate those 14 decimal place coefficients (or higher precision if desired). The 14 decimal place coefficients are just the 4 decimal place constants from BT.2020 run through the weighting to matrix calculations.

**Comment by nick-shaw** [comment]
```
>>> np.set_printoptions(suppress=True, formatter={'float_kind':'{:0.14f}'.format})
>>> matrix_YCbCr(K=WEIGHTS_YCBCR['ITU-R BT.2020'])
array([[1.00000000000000, -0.00000000000000, 1.47460000000000],
       [1.00000000000000, -0.16455312684366, -0.57135312684366],
       [1.00000000000000, 1.88140000000000, 0.00000000000000]])
```
This is exactly the matrix shown in the document.

**Review by nick-shaw — COMMENTED** [review]
Looks good to me, except perhaps the docstring should be more explicit that the returned matrix is the Y'CbCr to R'G'B' matrix, not the R'G'B' to Y'CbCr matrix. Other than that I am happy to approve the PR.

**Comment by KevinJW** [comment]
I haven't fully looked at this, but I wonder if [ITU T-REC-H.273](https://www.itu.int/rec/T-REC-H.273-201612-I/en) might have something to say on these, at least it states the expected behaviours for a number of the combinations. It does appear to be attempting to be definitive: `This Specification can be used to provide universal descriptions to assist interpretation of video and image signals following decoding or to describe the properties of these signals before they are encoded`

Kevin

**Comment by nick-shaw** [comment]
Not sure I completely follow, @KevinJW. Are you suggesting we adopt the  "Video Code Points" values as an (optional?) way of passing the `K` and `is_legal` arguments to the functions? This feels like it is more a part of the metadata layer that we do not yet have. Ideally the functions would also return metadata describing how the result was encoded.

**Comment by ValZapod** [comment]
> adopt the "Video Code Points" values as an

That is a bad idea, unless you wanna attach ffmpeg to yourself and become a new super video player... You can, BTW, considering ;)

> This is exactly the matrix shown in the document.

Yeah, nice. LGTM, then! BTW, can you add Kodak Photocd quantization? See https://github.com/DavidGriffith/finx/blob/17825bf28b2351f96867b34a7dc39f7997e2f9ff/nx-X11/programs/Xserver/XIE/mixie/process/mprgb.c#L1004 and this doc http://scarse.sourceforge.net/docs/kodak/pcd-045.pdf

> 1.099296826809442... and β has the value 0.018053968510807

This is BTW used in ffmpeg, just FYI.
https://github.com/FFmpeg/FFmpeg/blob/069d2b4a50a6eb2f925f36884e6b9bd9a1e54670/libavutil/color_utils.c#L58

While you use less precise https://github.com/colour-science/colour/search?q=0.018

**Comment by nick-shaw** [comment]
> BTW, can you add Kodak Photocd quantization?

The `RGB_to_YCbCr` function can already use arbitrary output scaling and offsets, using the `out_range` argument. See [here](https://colour.readthedocs.io/en/latest/generated/colour.RGB_to_YCbCr.html?highlight=out_range) for details. So the PhotoCD quantisation could be added using that together with the `out_int` argument.

**Comment by KelSolaar** [comment]
Thanks for the review @nick-shaw! I addressed the docstring notes and rebased on-top of develop. I will merge after the tests pass.

**Comment by KevinJW** [comment]
The numbers in that line in FFmpeg would be my "fault", can't remember exactly what source I used for it

Kevin

**Comment by ValZapod** [comment]
> FFmpeg would be my "fault", can't remember exactly what source I used for it

H.273, of course! Or H.264, as it was there before that.

**Pull request merged**
