### PR TITLE
PR: Update "colour.CIECAM02_to_XYZ" definition signature to use "colour.CIECAM02_Specification" class.

### PR DESCRIPTION
**Pull request by KelSolaar**
References #323.

### CODE REVIEW

**Comment by crowsonkb** [comment]
So instances of CIECAM02_Specification are now easy for the user to create, and the reverse mode uses JCh if C is present, otherwise JMh? This looks reasonable...

**Comment by KelSolaar** [comment]
Yes, that is pretty much it, we can tune/alter the logical behaviour at the entrance of the function to whatever we feel is the best.

**Comment by KelSolaar** [comment]
I added a new `colour.as_namedtuple` definition that attempts to convert given *array_like*, *Mapping* or *Numpy* structured array to *namedtuple*, thus it should be even easier to feed `colour. CIECAM02_to_XYZ` definition.

**Comment by MichaelMauderer** [comment]
Looks good, but it seems we are not testing lines 375 and 377.

**Comment by KelSolaar** [comment]
Good catch! I wanted to do it, was not sure how to inject that in the fixtures, decided to implement in priority `colour.as_namedtuple` and completely forgot going back to it.

**Comment by KelSolaar** [comment]
So basically we have to find a smart way, i.e. keeping things elegant, to run two tests by switching `C` here for `M`: https://github.com/colour-science/colour/blob/e5648db9148a7f62863e8832e01a43d6a83c6360/colour/appearance/tests/tests_ciecam02.py#L110-L110

Something I was thinking was to maybe have multiple `ColourAppearanceModelTest.output_specification_from_data` methods we could iterate on here: https://github.com/colour-science/colour/blob/cdbffd063b0c44bb32d752b01647137871434851/colour/appearance/tests/common.py#L133-L133

We could find them through pattern matching them while introspecting the object methods. What do you think?

**Comment by KelSolaar** [comment]
Well, turns out that `ColourAppearanceModelTest.output_specification_from_data` method is reimplemented for CIECAM02 reverse model, made things much easier. I will wait for the unit tests result and merge the PR accordingly as you approved the changes.

**Pull request merged**
