### PR TITLE
Fix divide by zero in ciecam02.py temporary_magnitude_quantity_reverse()

### PR DESCRIPTION
**Pull request by crowsonkb**
Ensure J cannot be below 1e-16 in temporary_magnitude_quantity_reverse().

### CODE REVIEW

**Comment by KelSolaar** [comment]
@crowsonkb : Thanks!

What about using `np.finfo(np.float_).resolution` in place of *1e-16*. On my platform it is actually *1.0000000000000001e-15*

@MichaelMauderer : What do you think?

**Comment by crowsonkb** [comment]
That seems reasonable. I was trying for something easy to type that was somewhere around float64 machine epsilon (~2.220e-16). That and 1e-8 is my usual epsilon when working with float32 data and 16 is twice that.

**Comment by MichaelMauderer** [comment]
Just had a look what might be the elegant solution and came across this: https://stackoverflow.com/questions/38477908/smallest-positive-float64-number

**Comment by KelSolaar** [comment]
`np.finfo(np.float_).eps` looks good!

**Comment by KelSolaar** [comment]
That could be a good opportunity to amend that one too: https://github.com/colour-science/colour/blob/develop/colour/constants/common.py#L38

**Comment by KelSolaar** [comment]
Thanks a lot!

**Pull request merged**
