### PR TITLE
PR: Improve initialization time of "Signal", a core component of "Colour".

### PR DESCRIPTION
**Pull request by tjdcs**
# Summary

This PR implements a performance improvement for `Signal` in `signal.py`. 

The initialization of _function, the private backing attribute for the `function` property, is relatively expensive. This performance issue was discovered when creating an MSDS object from a long list of SpectralDistributions or large ndarrays. The _create_function is invoked frequently when not needed. This PR updates relavent code to always use the function property. the function property has been changed to only invoke _create_function if the _function property has been invalidated (by setting it equal to None). If the function property is never accessed, then the relevant initialization does not take place (lazy initialization)

Under some conditions, this change results in a 90% reduction in Signal initialization run time

# Preflight

**Code Style and Quality**

- [x] Unit tests have been implemented and passed.
- [x] Mypy static checking has been run and passed.
- [x] Pre-commit hooks have been run and passed.
- [N/A] New transformations have been added to the *Automatic Colour Conversion Graph*.
- [N/A] New transformations have been exported to the relevant namespaces, e.g. `colour`, `colour.models`.

**Documentation**

- [N/A] New features are documented along with examples if relevant.
- [N/A] The documentation is [Sphinx](https://www.sphinx-doc.org/en/master/) and [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant.

### CODE REVIEW

**Comment by tjdcs** [comment]
Looks like this is well formed now.

**Comment by tjdcs** [comment]
@KelSolaar Other than the issue with static type checking (looks like something related to a new version of pip and an old installation method from a dependency) this is ready to merge.

**Comment by KelSolaar** [comment]
Hey @tjdcs,

Thank you! Two notes:

- The Static Typing issue is because we need to `cast` the return value of the `function` method to a `Callable`:

```python
    @property
    def function(self) -> Callable:
        """
        Getter property for the continuous signal callable.

        Returns
        -------
        Callable
            Continuous signal callable.
        """

        if self._function is None:
            self._create_function()

        return cast(Callable, self._function)
```

- Given that the `_create_function` is only used once now, we should probably move its code inside the `function` method directly.

**Comment by KelSolaar** [comment]
Thank you!

There are some issues with GH so I cannot comment on the changes directly, anyway, the `Callable | None` construct was introduced in [Python 3.10](https://mypy.readthedocs.io/en/stable/kinds_of_types.html#x-y-syntax-for-unions) so we tend to use the longer `Union[Callable, None]` form for now. I will merge and fix in a subsequent commit!

**Pull request merged**
