### PR TITLE
PR: Add "Munsell Renotation System" reference illuminant in the data header.

### PR DESCRIPTION
**Pull request by aurelienpierre**
# Summary

Quick addition in docstring, since I had to research this information myself, about the illuminant of the Munsell dataset renotation.

# Preflight

**Code Style and Quality**

- [ ] Unit tests have been implemented and passed.
- [ ] Mypy static checking has been run and passed.
- [ ] Pre-commit hooks have been run and passed.
- [ ] New transformations have been added to the *Automatic Colour Conversion Graph*.
- [ ] New transformations have been exported to the relevant namespaces, e.g. `colour`, `colour.models`.

**Documentation**

- [ ] New features are documented along with examples if relevant.
- [ ] The documentation is [Sphinx](https://www.sphinx-doc.org/en/master/) and [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant.

### CODE REVIEW

**Comment by KelSolaar** [comment]
Hi @aurelienpierre,

Thanks, the reference illuminant is documented here: https://github.com/colour-science/colour/blob/b9b5504355257757494a7f6f19e19d8ff09f7545/colour/notation/munsell.py#L259 but it is also good to have it next to the data!

I will merge the PR as is even though the tests do not pass and the docstring addition needs to be replicated in the two other modules.

Cheers,

Thomas

**Comment by aurelienpierre** [comment]
> Thanks, the reference illuminant is documented here: 

No problem, but the doc doesn't seem to show it (or the Sphinx search engine is not helpful).

**Comment by KelSolaar** [comment]
Ah this is a good point, this part of the module documentation is not surfaced by our current Sphinx setup. We should copy part of it here: https://colour.readthedocs.io/en/develop/generated/colour.MUNSELL_COLOURS.html#colour.MUNSELL_COLOURS

**Comment by KelSolaar** [comment]
I surfaced the information in the above page!

**Pull request merged**
